services:
  app:
    image: wisdomwork/ecode-admin:latest
    platform: linux/x86_64
    ports:
      - '4001:80'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
